name: yarn test

on:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  deploy_testtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout by push
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: '@xxxxjp'
          cache: 'yarn'
      # - name: Setup nx
      #   run: |
      #     yarn global add nx
      #     yarn install
      # - name: Build one app
      #   run: nx run nextapp:build
      # dummy


