name: workflows test2 in feature/1 branch

on:
  push:
    branches:
      - main

jobs:
  deploy_testtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout by push
        uses: actions/checkout@v3
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: '@xxxxjp'
          cache: 'yarn'
          cache-dependency-path: ./test-repo2/yarn.lock
      - name: Setup nx
        run: |
          yarn install
          yarn global add nx
        working-directory: ./test-repo2
#       - name: Build one app
#         run: nx run nextapp:build
#         working-directory: ./test-repo2
